{% set name = "cudatoolkit-dev" %}
{% set version = "10.0" %}
{% set version_build = "130" %}
{% set driver_version = "410.48" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ./

build:
  script: python build.py {{ version }} {{ version_build }} {{ driver_version }}
  number: 2
  skip: True  # [win]

requirements:
  host:
    - conda
    - python

test:
  commands:
    - test -f $PREFIX/bin/cudatoolkit-dev-post-install.py  # [unix]
    - test -f $PREFIX/bin/cudatoolkit-dev-extra-args.json  # [unix]
    - test -d $PREFIX/scripts/activate.d  # [unix]
    - test -d $PREFIX/scripts/deactivate.d  # [unix]

about:
  home: "https://developer.nvidia.com"
  license: "other"
  license_family: "other"
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: "Develop, Optimize and Deploy GPU-accelerated Apps"
  description: |
    The NVIDIA CUDA Toolkit provides a development environment for creating
    high performance GPU-accelerated applications. With the CUDA Toolkit,
    you can develop, optimize and deploy your applications on GPU-accelerated
    embedded systems, desktop workstations, enterprise data centers,
    cloud-based platforms and HPC supercomputers. The toolkit includes
    GPU-accelerated libraries, debugging and optimization tools,
    a C/C++ compiler and a runtime library to deploy your application.
    This package consists of a post-install script that downloads and
    installs the full cuda toolkit(compiler, libraries, with the exception of cuda drivers).
  doc_url: https://developer.nvidia.com/cuda-toolkit
  dev_url: https://developer.nvidia.com/cuda-toolkit

extra:
  recipe-maintainers:
    - andersy005
    - scopatz
    - xmnlab
