{% set name = "cudatoolkit-dev" %}
{% set release = "11.4" %}
{% set version_build = "0" %}
{% set driver_version = "470.42.01" %}

package:
  name: {{ name|lower }}
  version: {{ release }}.{{ version_build }}

source:
  path: ./

build:
  script: python build.py {{ release }} {{ version_build }} {{ driver_version }}
  number: 0
  skip: True  # [win]
  skip: True  # [osx]

requirements:
  build:
    - python
    - wget
  run:
    - python

test:
  requires:
    - numba
    - wget
    - {{ compiler('c') }}

about:
  home: "https://developer.nvidia.com"
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: "Develop, Optimize and Deploy GPU-accelerated Apps"
  description: |
    The NVIDIA CUDA Toolkit provides a development environment for creating
    high performance GPU-accelerated applications. With the CUDA Toolkit,
    you can develop, optimize and deploy your applications on GPU-accelerated
    embedded systems, desktop workstations, enterprise data centers,
    cloud-based platforms and HPC supercomputers. The toolkit includes
    GPU-accelerated libraries, debugging and optimization tools,
    a C/C++ compiler and a runtime library to deploy your application.
    This package consists of a post-install script that downloads and
    installs the full cuda toolkit(compiler, libraries, with the exception of cuda drivers).
  doc_url: https://developer.nvidia.com/cuda-toolkit
  dev_url: https://developer.nvidia.com/cuda-toolkit

extra:
  recipe-maintainers:
    - andersy005
    - scopatz
    - xmnlab
    - AgrawalAmey
