{% set name = "cudatoolkit-dev" %}
{% set release = "11.0" %}
{% set version_build = "3" %}
{% set driver_version = "450.51.06" %}
{% set win_driver_version = "451.82" %}

package:
  name: {{ name|lower }}
  version: {{ release }}.{{ version_build }}

source:
  path: ./

build:
  script: python build.py {{ release }} {{ version_build }} {{ driver_version }}  # [linux]
  script: python build.py {{ release }} {{ version_build }} {{ win_driver_version }}  # [win]
  number: 3
  skip: True  # [osx]

requirements:
  build:
    - python
    - wget  # [linux]
    - curl  # [win]
    - 7zip  # [win]
  run:
    - python

test:
  requires:
    - numba
    - wget  # [linux]
    - curl  # [win]
    - 7zip  # [win]
    - {{ compiler('c') }}

about:
  home: "https://developer.nvidia.com"
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: "Develop, Optimize and Deploy GPU-accelerated Apps"
  description: |
    The NVIDIA CUDA Toolkit provides a development environment for creating
    high performance GPU-accelerated applications. With the CUDA Toolkit,
    you can develop, optimize and deploy your applications on GPU-accelerated
    embedded systems, desktop workstations, enterprise data centers,
    cloud-based platforms and HPC supercomputers. The toolkit includes
    GPU-accelerated libraries, debugging and optimization tools,
    a C/C++ compiler and a runtime library to deploy your application.
    This package consists of a post-install script that downloads and
    installs the full cuda toolkit(compiler, libraries, with the exception of cuda drivers).
  doc_url: https://developer.nvidia.com/cuda-toolkit
  dev_url: https://developer.nvidia.com/cuda-toolkit

extra:
  recipe-maintainers:
    - andersy005
    - scopatz
    - xmnlab
    - AgrawalAmey
