travis:
  secure:
    BINSTAR_TOKEN: tFfTQiE8FXzyBtVV4PJ0ueRb4Emm6xj3wJeiiKDPOls2uvEe2/KEhLAvemrWGZ65zEZeHlduFsW2oXz6JEYBiM4rfJg9r3POUfWK4mHaPSyKo8g1wmwfR7oFHo64nlQvT0FMzE/TzmK9KjRZAXkND9t0o6E/fsHYjrXvntuPL1cQDhHA1dK9ni+5ILgCGaPzkbPkvAxwFWVs0cfv8aZmTcEw1BerenkvrPGlLBHKRuhtOhsfa/bwuBKpckglPnhnKOSEMdjv3c/CmEHMbAAo1YzSgThXfJ9o0U7zGQC27O0a2ZlvM3BqbXUvOSkMTNPj46mpjIgMzo2IAoeaMZPuQYauAqfZanL8x2jtr27CywdMsOjYBL+L8n4TOoEDRd0kVWR5aK5Y4+Qu/3fmzEmbw64atpzUHi3Cn/Wx8i96GloGu16uepV6xqfkeNwyw7YwGHgfZcPfisfxMoS6my6PxKjqfQoCsStrtztf820Zgnr2HwGNmZGdZtfhs0mCDeTyyc0I6HX6OzCvOZk5AOW9Pe8oIDhkKE5na/CnbssRnHz5xZmDjz2NQkhGSqEs5Rth7EsSRHWhDvhBWPaYyI9AR6nI8uPL7MTGOIMIBMP6j2LsPE2uNEfAxBP6nxIGKpdmAozW0TLTxa6d7vuB9Si7NP7QADjVl7kc3hE0u96s7Dg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1

docker:
  executable: docker
  image: "condaforge/linux-anvil"
  command: "bash"
  interactive: True